### Repaso Clase 8: Introducción práctica a NumPy

### 1. ¿Qué problema resuelve NumPy?

Supongamos que tenemos los ingresos mensuales de varias personas y necesitamos aumentar cada valor en 10%.

Con una lista de Python podemos resolverlo mediante un ciclo Esto es correcto y utiliza conocimientos ya estudiados.

In [5]:
# Ejm:
ingresos = [1200, 1500, 1800, 2100, 2500]

ingresos_aumentados = []

for ingreso in ingresos:
    nuevo_ingreso = ingreso * 1.10
    ingresos_aumentados.append(nuevo_ingreso)
    
print("Ingresos orifinales:", ingresos)
print("ingresos con aumento", ingresos_aumentados)

Ingresos orifinales: [1200, 1500, 1800, 2100, 2500]
ingresos con aumento [1320.0, 1650.0000000000002, 1980.0000000000002, 2310.0, 2750.0]


No hay nada incorrecto en esta solución: Sin embargo, cuando trabajamos con cientos de miles o millones de valores, necesitamos una forma más directa y especializada.

NumPy permite aplicar la operación a todo el array de una sola vez.

In [6]:
import numpy as np

ingresos_np = np.array([1200, 1500, 1800, 2100, 2500])
ingresos_aumentados_np = ingresos_np * 1.10

print("Array original:", ingresos_np)
print("Array con aumento", ingresos_aumentados_np)

Array original: [1200 1500 1800 2100 2500]
Array con aumento [1320. 1650. 1980. 2310. 2750.]


#### ¿Qué observamos?

En NumPy no fue necesario un ciclo *for* para realizar el aumento.

A este modo de trabajo se le llama operación vectorizada.

#### ¿Qué es NumPy?

NumPy significa **Numeral Python**. Es una biblioteca orientada al manejo eficiente de array numéricos.

Su estructura principal es el objeto:
- ndarray

El término significa n_dimensional array, es decir, array de *n* dimensiones.

In [7]:
print("Tipo de una lista de Python:", type(ingresos))
print("Tipo de un array Numpy:", type(ingresos_np) )

Tipo de una lista de Python: <class 'list'>
Tipo de un array Numpy: <class 'numpy.ndarray'>


### 2. Importaciones de NumPy

In [ ]:
# import numpy as np

### 3. Creación de array

#### 3.1 Crear un array desde una lista

La función np.array recibe una lista u otra colección de datos y la transforma en un array NumPy

In [8]:
# Ejm: 
edades = np.array([18, 25, 31, 40, 52])

print(edades)
print(type(edades))

[18 25 31 40 52]
<class 'numpy.ndarray'>


El array anterior tiene una dimensión. Podemos imaginarlo como una fila de valores.

[18, 25, 31, 40, 52]

#### 3.2 Array de dos dimensiones

Un array de dos dimensiones puede presentar una tabla o matriz.

En el siguiente ejemplo:
- cada lista interna representa una fila.
- cada valor representa una columna.

In [ ]:
# Ejm: 
poblacion = np.array([
    [120000, 125000],  # Fila
    [80000, 84000],
    [150000, 162000]
])    # Columna

print(poblacion)

[[120000 125000]
 [ 80000  84000]
 [150000 162000]]


#### 3.3 Arrays creados automáticamente

NumPy contiene funciones útiles para crear arrays sin escribir manualmente cada elemento.

In [ ]:
ceros = np.zeros(5)
unos = np.ones(5)
secuencia = np.arange(1, 11)
puntos = np.linspace(0, 1, 5)

print("Cinco ceros:", ceros)
print("Cinco unos:", unos)
print("Números del 1 al 10:", secuencia)
print("Cinco puntos entre 0 y 1:", puntos)

# np.linspace(0, 1, 5)
# Crea cinco valores igualmente espaciados entre 0 y 1, incluyendo ambos extremos.
# Estas funciones son útiles para inicializar estructuras, construir secuencias y preparar datos para cálculos.

Cinco ceros: [0. 0. 0. 0. 0.]
Cinco unos: [1. 1. 1. 1. 1.]
Números del 1 al 10: [ 1  2  3  4  5  6  7  8  9 10]
Cinco puntos entre 0 y 1: [0.   0.25 0.5  0.75 1.  ]


### 4. Propiedades principales de un array

Para comprender un array es necesario responder cuatro preguntas:
- ¿Cuántas dimensiones tiene?    -> *ndim*
- ¿Cuál es su forma?             -> *shape*
- ¿Cuántos elementos contiene?   -> *size*
- ¿Qué tipos de datos almacena?  -> *dtype*

In [ ]:
datos = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Arrays:")
print(datos)

print("\nNúmero de dimensiones:", datos.ndim)
print("Forma de array:", datos.shape)  # (2, 3): 2 filas, 3 columnas
print("Cantidad total de elementos:", datos.size)  # 2x3 = 6 elementos
print("Qué tipo de datos almacena:", datos.dtype)

Arrays:
[[10 20 30]
 [40 50 60]]

Número de dimensiones: 2
Forma de array: (2, 3)
Cantidad total de elementos: 6
Qué tipo de datos almacena: int64


Diferencia entre 'ndim', 'shape' y 'size':
- Propiedad   |       Pregunta que responde
- ndim       ->      ¿Cuántas dimensiones tiene?
- shape      ->      ¿Cuántas filas y columnas tiene?
- size       ->      ¿Cuántos elementos contiene en total?
- dtype      ->      ¿Qué tipo de datos almacena?

#### 4.1 un array utiliza un tipo común

En una lista de Python pueden coexistir diferentes tipos de datos.

En NumPy, los elementos del array normalmente se convierten en un tipo común

In [15]:
mezcla_numerica = np.array([10, 20.5, 30])

print(mezcla_numerica)
print("tipo comun:", mezcla_numerica.dtype)

[10.  20.5 30. ]
tipo comun: float64


Aunque algunos valores fueron escritos como enteros , NumPy utiliza un tipo decimal para evitar perder información.

Esto es importante porque los arrays NumPy están diseñados para realizar cálculos uniformes y eficientes.


### 5. Acceso a los elementos de un arrreglo

NumPy utiliza índices, igual que las listas de Python.

El primer elemento se encuestra en la posición 0.

In [17]:
# Ejm:
ventas = np.array([150, 175, 300, 250])

print("Primer elemento:", ventas[0])
print("Segundo elemento:", ventas[1])
print("Último elemento:", ventas[-1])

Primer elemento: 150
Segundo elemento: 175
Último elemento: 250


#### 5.1 Segmentación o slicing

La expresión:
- ventas[inicio:fin]
Selecciona desde la posición inicio hasta una posición anterior a fin.

In [18]:
# Ejm:
print("Elementos desde la posición 1 hasta antes de la 4:", ventas[0:4])
print("primeros 3 elementos.", ventas[:3])
print("Desde la posición 2 hasta el final:", ventas[2:])

Elementos desde la posición 1 hasta antes de la 4: [150 175 300 250]
primeros 3 elementos. [150 175 300]
Desde la posición 2 hasta el final: [300 250]


#### 5.2 Acceso en arrays de dos dimensiones

En un arreglo bidimensional usamos:
- matriz[fila, columna]
Los índices de filas y columnas también comienzan en cero.

In [23]:
# Ejm:
matriz = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Matriz completa:")
print(matriz)

print("\nElementos de la fila 0, columna 1:", matriz[0, 1])
print("Elementos de la fila 2, columna 2:", matriz[2, 2])
print("Primer fila:", matriz[0, :])
print("Segunda columna.", matriz[:, 1])

Matriz completa:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Elementos de la fila 0, columna 1: 20
Elementos de la fila 2, columna 2: 90
Primer fila: [10 20 30]
Segunda columna. [20 50 80]


### 6. Modificación de elementos

Los elementos de un arrray pueden cambiarse utilizando su índice.

In [24]:
# Ejm:
puntajes = np.array([12, 15, 10, 18, 14])

print("Antes de modificar:", puntajes)

puntajes[2] = 16

print("Después de modificar:", puntajes)

Antes de modificar: [12 15 10 18 14]
Después de modificar: [12 15 16 18 14]


In [25]:
puntajes[-1] = 24
print("Otra modificación:", puntajes)

Otra modificación: [12 15 16 18 24]


También podemos modificar varios elementos mediante slicing.

In [28]:
puntajes[0:2] = 20

print("Después de modificar los dos priemros valores.", puntajes)

Después de modificar los dos priemros valores. [20 20 16 18 24]


### 7. Filtrado mediante condiciones

Una de las condiciones más útiles de NumPy es seleccionar los elementos que cumplen una condición.

primero podemos evaluar una condición sobre todo el array

In [30]:
# EJm:
ingresos = np.array([950, 1200, 1800, 2200, 3000])

condicion = ingresos > 1500

print("ingresos:", ingresos)
print("¿Es mayor que 1500?:", condicion)

ingresos: [ 950 1200 1800 2200 3000]
¿Es mayor que 1500?: [False False  True  True  True]


Podemos utilizar directamente esa condición para extraer los valores.

In [31]:
ingresos_mayores = ingresos[ingresos > 1500]

print("Ingresos mayores que 1500:", ingresos_mayores)

Ingresos mayores que 1500: [1800 2200 3000]


Este procedimiento se conoce como **filtrado booleano**

La expresión:

- ingresos > 1500

construye una máscara de valores verdaderos y falsos.

Luego:

- ingresos[ingresos > 1500]

devuelve únicamente los elementos cuyas posiciones tienen el valor True.