### Repaso Clase 8: Introducción práctica a NumPy

### 1. ¿Qué problema resuelve NumPy?

Supongamos que tenemos los ingresos mensuales de varias personas y necesitamos aumentar cada valor en 10%.

Con una lista de Python podemos resolverlo mediante un ciclo Esto es correcto y utiliza conocimientos ya estudiados.

In [3]:
# Ejm:
ingresos = [1200, 1500, 1800, 2100, 2500]

ingresos_aumentados = []

for ingreso in ingresos:
    nuevo_ingreso = ingreso * 1.10
    ingresos_aumentados.append(nuevo_ingreso)
    
print("Ingresos orifinales:", ingresos)
print("ingresos con aumento", ingresos_aumentados)

Ingresos orifinales: [1200, 1500, 1800, 2100, 2500]
ingresos con aumento [1320.0, 1650.0000000000002, 1980.0000000000002, 2310.0, 2750.0]


No hay nada incorrecto en esta solución: Sin embargo, cuando trabajamos con cientos de miles o millones de valores, necesitamos una forma más directa y especializada.

NumPy permite aplicar la operación a todo el array de una sola vez.

In [4]:
import numpy as np

ingresos_np = np.array([1200, 1500, 1800, 2100, 2500])
ingresos_aumentados_np = ingresos_np * 1.10

print("Array original:", ingresos_np)
print("Array con aumento", ingresos_aumentados_np)

Array original: [1200 1500 1800 2100 2500]
Array con aumento [1320. 1650. 1980. 2310. 2750.]


#### ¿Qué observamos?

En NumPy no fue necesario un ciclo *for* para realizar el aumento.

A este modo de trabajo se le llama operación vectorizada.

#### ¿Qué es NumPy?

NumPy significa **Numeral Python**. Es una biblioteca orientada al manejo eficiente de array numéricos.

Su estructura principal es el objeto:
- ndarray

El término significa n_dimensional array, es decir, array de *n* dimensiones.

In [5]:
print("Tipo de una lista de Python:", type(ingresos))
print("Tipo de un array Numpy:", type(ingresos_np) )

Tipo de una lista de Python: <class 'list'>
Tipo de un array Numpy: <class 'numpy.ndarray'>


### 2. Importaciones de NumPy

In [6]:
# import numpy as np

### 3. Creación de array

#### 3.1 Crear un array desde una lista

La función np.array recibe una lista u otra colección de datos y la transforma en un array NumPy

In [7]:
# Ejm: 
edades = np.array([18, 25, 31, 40, 52])

print(edades)
print(type(edades))

[18 25 31 40 52]
<class 'numpy.ndarray'>


El array anterior tiene una dimensión. Podemos imaginarlo como una fila de valores.

[18, 25, 31, 40, 52]

#### 3.2 Array de dos dimensiones

Un array de dos dimensiones puede presentar una tabla o matriz.

En el siguiente ejemplo:
- cada lista interna representa una fila.
- cada valor representa una columna.

In [8]:
# Ejm: 
poblacion = np.array([
    [120000, 125000],  # Fila
    [80000, 84000],
    [150000, 162000]
])    # Columna

print(poblacion)

[[120000 125000]
 [ 80000  84000]
 [150000 162000]]


#### 3.3 Arrays creados automáticamente

NumPy contiene funciones útiles para crear arrays sin escribir manualmente cada elemento.

In [9]:
ceros = np.zeros(5)
unos = np.ones(5)
secuencia = np.arange(1, 11)
puntos = np.linspace(0, 1, 5)

print("Cinco ceros:", ceros)
print("Cinco unos:", unos)
print("Números del 1 al 10:", secuencia)
print("Cinco puntos entre 0 y 1:", puntos)

# np.linspace(0, 1, 5)
# Crea cinco valores igualmente espaciados entre 0 y 1, incluyendo ambos extremos.
# Estas funciones son útiles para inicializar estructuras, construir secuencias y preparar datos para cálculos.

Cinco ceros: [0. 0. 0. 0. 0.]
Cinco unos: [1. 1. 1. 1. 1.]
Números del 1 al 10: [ 1  2  3  4  5  6  7  8  9 10]
Cinco puntos entre 0 y 1: [0.   0.25 0.5  0.75 1.  ]


### 4. Propiedades principales de un array

Para comprender un array es necesario responder cuatro preguntas:
- ¿Cuántas dimensiones tiene?    -> *ndim*
- ¿Cuál es su forma?             -> *shape*
- ¿Cuántos elementos contiene?   -> *size*
- ¿Qué tipos de datos almacena?  -> *dtype*

In [10]:
datos = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Arrays:")
print(datos)

print("\nNúmero de dimensiones:", datos.ndim)
print("Forma de array:", datos.shape)  # (2, 3): 2 filas, 3 columnas
print("Cantidad total de elementos:", datos.size)  # 2x3 = 6 elementos
print("Qué tipo de datos almacena:", datos.dtype)

Arrays:
[[10 20 30]
 [40 50 60]]

Número de dimensiones: 2
Forma de array: (2, 3)
Cantidad total de elementos: 6
Qué tipo de datos almacena: int64


Diferencia entre 'ndim', 'shape' y 'size':
- Propiedad   |       Pregunta que responde
- ndim       ->      ¿Cuántas dimensiones tiene?
- shape      ->      ¿Cuántas filas y columnas tiene?
- size       ->      ¿Cuántos elementos contiene en total?
- dtype      ->      ¿Qué tipo de datos almacena?

#### 4.1 un array utiliza un tipo común

En una lista de Python pueden coexistir diferentes tipos de datos.

En NumPy, los elementos del array normalmente se convierten en un tipo común

In [11]:
mezcla_numerica = np.array([10, 20.5, 30])

print(mezcla_numerica)
print("tipo comun:", mezcla_numerica.dtype)

[10.  20.5 30. ]
tipo comun: float64


Aunque algunos valores fueron escritos como enteros , NumPy utiliza un tipo decimal para evitar perder información.

Esto es importante porque los arrays NumPy están diseñados para realizar cálculos uniformes y eficientes.


### 5. Acceso a los elementos de un arrreglo

NumPy utiliza índices, igual que las listas de Python.

El primer elemento se encuestra en la posición 0.

In [12]:
# Ejm:
ventas = np.array([150, 175, 300, 250])

print("Primer elemento:", ventas[0])
print("Segundo elemento:", ventas[1])
print("Último elemento:", ventas[-1])

Primer elemento: 150
Segundo elemento: 175
Último elemento: 250


#### 5.1 Segmentación o slicing

La expresión:
- ventas[inicio:fin]
Selecciona desde la posición inicio hasta una posición anterior a fin.

In [13]:
# Ejm:
print("Elementos desde la posición 1 hasta antes de la 4:", ventas[0:4])
print("primeros 3 elementos.", ventas[:3])
print("Desde la posición 2 hasta el final:", ventas[2:])

Elementos desde la posición 1 hasta antes de la 4: [150 175 300 250]
primeros 3 elementos. [150 175 300]
Desde la posición 2 hasta el final: [300 250]


#### 5.2 Acceso en arrays de dos dimensiones

En un arreglo bidimensional usamos:
- matriz[fila, columna]
Los índices de filas y columnas también comienzan en cero.

In [14]:
# Ejm:
matriz = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Matriz completa:")
print(matriz)

print("\nElementos de la fila 0, columna 1:", matriz[0, 1])
print("Elementos de la fila 2, columna 2:", matriz[2, 2])
print("Primer fila:", matriz[0, :])
print("Segunda columna.", matriz[:, 1])

Matriz completa:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Elementos de la fila 0, columna 1: 20
Elementos de la fila 2, columna 2: 90
Primer fila: [10 20 30]
Segunda columna. [20 50 80]


### 6. Modificación de elementos

Los elementos de un arrray pueden cambiarse utilizando su índice.

In [15]:
# Ejm:
puntajes = np.array([12, 15, 10, 18, 14])

print("Antes de modificar:", puntajes)

puntajes[2] = 16

print("Después de modificar:", puntajes)

Antes de modificar: [12 15 10 18 14]
Después de modificar: [12 15 16 18 14]


In [16]:
puntajes[-1] = 24
print("Otra modificación:", puntajes)

Otra modificación: [12 15 16 18 24]


También podemos modificar varios elementos mediante slicing.

In [17]:
puntajes[0:2] = 20

print("Después de modificar los dos priemros valores.", puntajes)

Después de modificar los dos priemros valores. [20 20 16 18 24]


### 7. Filtrado mediante condiciones

Una de las condiciones más útiles de NumPy es seleccionar los elementos que cumplen una condición.

primero podemos evaluar una condición sobre todo el array

In [18]:
# EJm:
ingresos = np.array([950, 1200, 1800, 2200, 3000])

condicion = ingresos > 1500

print("ingresos:", ingresos)
print("¿Es mayor que 1500?:", condicion)

ingresos: [ 950 1200 1800 2200 3000]
¿Es mayor que 1500?: [False False  True  True  True]


Podemos utilizar directamente esa condición para extraer los valores.

In [19]:
ingresos_mayores = ingresos[ingresos > 1500]

print("Ingresos mayores que 1500:", ingresos_mayores)

Ingresos mayores que 1500: [1800 2200 3000]


Este procedimiento se conoce como **filtrado booleano**

La expresión:

- ingresos > 1500

construye una máscara de valores verdaderos y falsos.

Luego:

- ingresos[ingresos > 1500]

devuelve únicamente los elementos cuyas posiciones tienen el valor True.

In [20]:
# Ejm:
edades = np.array([12, 45, 23, 64, 53, 34, 23, 14, 18, 45, 37, 27])

edades[edades >= 18]

mayores_edad = edades[edades >= 18]
print("Personas de mayor edad:", mayores_edad)
print("\nDimensiones:", edades.ndim)
print("Cuántas filas y columnas:", edades.shape)
print("Elementos en total:", edades.size)
print("Tipo de datos almacenado:", edades.dtype)

Personas de mayor edad: [45 23 64 53 34 23 18 45 37 27]

Dimensiones: 1
Cuántas filas y columnas: (12,)
Elementos en total: 12
Tipo de datos almacenado: int64


In [21]:
notas = np.array([12, 14, 15, 11, 9, 16, 20, 10, 17, 4])

notas_aprobadas = notas[notas >= 11]

print("Notas en egeneral:", notas)
print("Notas aprobadas:", notas_aprobadas)
print("\nDimensión:", notas.ndim)
print("Número de filas y columnas:", notas.shape)
print("Total de elementos:", notas.size)
print("Tipo de datos almacenados.", notas.dtype)

Notas en egeneral: [12 14 15 11  9 16 20 10 17  4]
Notas aprobadas: [12 14 15 11 16 20 17]

Dimensión: 1
Número de filas y columnas: (10,)
Total de elementos: 10
Tipo de datos almacenados. int64


### 8. Operaciones vectorizadas

Una operación vectorizada se aplica a todos los elementos del array.

No necesitamos recorrer los valores mediante un ciclo explícito.

In [22]:
# Ejm:
datos = np.array([10, 20, 30, 40])

print("Array original", datos)
print("Sumar 5:", datos + 5)
print("Multiplicar por 2:", datos * 2)
print("Dividir entre 10:", datos / 10)
print("Elevar al cuadrado:", datos ** 2)

Array original [10 20 30 40]
Sumar 5: [15 25 35 45]
Multiplicar por 2: [20 40 60 80]
Dividir entre 10: [1. 2. 3. 4.]
Elevar al cuadrado: [ 100  400  900 1600]


#### 8.1 Diferencia entre una lista y array NumPy

La multiplicación tiene comportamientos distintos.

In [23]:
# Ejm:
lista_python = [1, 2, 3]
array_numpy = np.array([1, 2, 3])

print("Lista multiplicada por 2:", lista_python * 2)
print("Array multiplicada por 2:", array_numpy * 2)

Lista multiplicada por 2: [1, 2, 3, 1, 2, 3]
Array multiplicada por 2: [2 4 6]


Interpretación:
- Una lista -> repite el contenido
- Un array -> multiplica cada elemento

Esta diferencioa es fundamental

#### 8.2 Operaciones entre arrays

También podemos operar dos arrays elemento por elemento.

Para ello deben tener formas compatibles.

In [24]:
# Ejm:
ventas_enero = np.array([100, 150, 200, 250])
ventas_febrero = np.array([120, 140, 230, 270])

diferencia = ventas_febrero - ventas_enero
total_dos_meses = ventas_enero + ventas_febrero

print("Venta de enero:", ventas_enero)
print("ventas de febrero:", ventas_febrero)
print("Diferencia febrero - enero:", diferencia)
print("Total de los dos meses:", total_dos_meses)

Venta de enero: [100 150 200 250]
ventas de febrero: [120 140 230 270]
Diferencia febrero - enero: [ 20 -10  30  20]
Total de los dos meses: [220 290 430 520]


In [25]:
# Ejm:
bolsa_de_lima_1 = np.array([2.3, 5.2, 0.1, 1.1, 0.2])
bolsa_de_lima_2 = np.array([0.1, 1.9, 2.0, 3.3, 4.3])

diferencia = bolsa_de_lima_2 - bolsa_de_lima_1
total_dos_dias = bolsa_de_lima_1 + bolsa_de_lima_2

print("Bolsa de Lima día 1:", bolsa_de_lima_1)
print("Bolsa de Lima día 2.", bolsa_de_lima_2)
print("Diferencia día 2 y día 1:", diferencia)
print("Total de los dos días.", total_dos_dias)

Bolsa de Lima día 1: [2.3 5.2 0.1 1.1 0.2]
Bolsa de Lima día 2. [0.1 1.9 2.  3.3 4.3]
Diferencia día 2 y día 1: [-2.2 -3.3  1.9  2.2  4.1]
Total de los dos días. [2.4 7.1 2.1 4.4 4.5]


### 9. Funciones estadísticas básicas

NumPy permite calcular resúmenes numéricos de forma directa.

In [26]:
# Ejm:
valores = np.array([10, 12, 15, 18, 20, 25])

print("Datos:", valores)
print("Suma:", np.sum(valores))
print("Promedio:", np.mean(valores))
print("Mínimo.", np.min(valores))
print("Máximo:", np.max(valores))
print("Mediana.", np.median(valores))
print("Desviación estándar.", np.std(valores))

Datos: [10 12 15 18 20 25]
Suma: 100
Promedio: 16.666666666666668
Mínimo. 10
Máximo: 25
Mediana. 16.5
Desviación estándar. 5.022173057773121


In [27]:
notas_inei = np.array([15, 20, 14, 5, 12, 17, 13, 9, 11, 17, 10, 19, 14, 12, 15, 3, 13, 7, 20])

print("ESTADÍSTICA DE NOTAS INEI")
print("--------------------------")
print("\nNotas en general:", notas_inei)
print("Suma:", np.sum(notas_inei))
print("Promedio.", np.mean(notas_inei))
print("Mínimo:", np.min(notas_inei))
print("Máximo:", np.max(notas_inei))
print("Mediana:", np.median(notas_inei))
print("Desviación estándar:", np.std(notas_inei))


ESTADÍSTICA DE NOTAS INEI
--------------------------

Notas en general: [15 20 14  5 12 17 13  9 11 17 10 19 14 12 15  3 13  7 20]
Suma: 246
Promedio. 12.947368421052632
Mínimo: 3
Máximo: 20
Mediana: 13.0
Desviación estándar: 4.627989039364339


### 10. Caso integrador: análisis de población distrital

Trabajaremos con un conjunto pequeñonde datos ficticios para aplicar los conceptos estudiados.

Tenemos cinco distritos y dos mediciones:
- población registrada;
- población proyectada.

El propósito es calcular:
- crecimiento absoluto;
- crecimiento porcentual;
- población promedio;
- distrito con mayor y menor población proyectada;
- distritos cuya población proyectada supera un límite.

In [28]:
distritos = np.array([
    "Distrito Norte",
    "Distrito Sur",
    "Distrito Este",
    "Distrito Oeste",
    "Distrito Centro"
])

poblacion_registrada = np.array([120000, 80000, 150000, 95000, 200000])
poblacion_proyectada = np.array([126000, 84000, 162000, 98000, 218000])

print("Distritos:")
print(distritos)
print("\nPoblación regsitrada:")
print(poblacion_registrada)
print("\nPoblación proyectada:")
print(poblacion_proyectada)

Distritos:
['Distrito Norte' 'Distrito Sur' 'Distrito Este' 'Distrito Oeste'
 'Distrito Centro']

Población regsitrada:
[120000  80000 150000  95000 200000]

Población proyectada:
[126000  84000 162000  98000 218000]


##### 10.1 Crecimiento absoluto

El crecimiento absoluto se calcula restando:
- población proyectada - población registrada

Como ambos arrray tienen la misma cantidad de elementos, NumPy realiza la resta posición opor posición.

In [29]:
crecimiento_absoluto = poblacion_proyectada - poblacion_registrada

print("Crecimiento absoluto por distrito:")
print(crecimiento_absoluto)

Crecimiento absoluto por distrito:
[ 6000  4000 12000  3000 18000]


##### 10.2 Crecimiento porcentual

La fórmula es:
- ((proyectada - registrada) / registrada) x 100

In [30]:
crecimiento_porcentual = (
    (poblacion_proyectada - poblacion_registrada)
    / poblacion_registrada
) * 100

print("Crecimiento porcentual:", crecimiento_porcentual)

# con dos decimáles
print("Crecimiento poblacional:", np.round(crecimiento_porcentual, 2))

#El arreglo original no se modifica; solamente se controla la forma en que se presenta los valores

Crecimiento porcentual: [5.         5.         8.         3.15789474 9.        ]
Crecimiento poblacional: [5.   5.   8.   3.16 9.  ]


##### 10.3 Promedio de población proyectada

In [31]:
promedio_proyectado = np.mean(poblacion_proyectada)

print("Población proyectada promedio:", promedio_proyectado)

Población proyectada promedio: 137600.0


##### 10.4 Distrito con mayor población proyectada

*np.argmax()* devuelve la posición del valor máximo.

Después usamos esa posición para consultar el nombre del distrito y su población

In [32]:
indice_mayor = np.argmax(poblacion_proyectada)

print("Posición del mayor valor:", indice_mayor)
print("Distrito con mayor población proyectada:", distritos[indice_mayor])
print("Población proyectada:", poblacion_proyectada[indice_mayor])

Posición del mayor valor: 4
Distrito con mayor población proyectada: Distrito Centro
Población proyectada: 218000


##### 10.5 Distrito con menor población proyectada

*np.argmin()* devuelve la posición del valor mínimo.

In [33]:
indice_menor = np.argmin(poblacion_proyectada)

print("Posición del menor valor:", indice_menor)
print("Distrito con menor poblacion proyectada:", distritos[indice_menor])
print("Población proyectada:", poblacion_proyectada[indice_menor])

Posición del menor valor: 1
Distrito con menor poblacion proyectada: Distrito Sur
Población proyectada: 84000


##### 10.6 Filtrar distritos con más de 100 000 habitantes proyectados

Primero se construye una condición booleano

In [35]:
supera_limite = poblacion_proyectada >= 100000

print("Condición booleana:")
print(supera_limite)

Condición booleana:
[ True False  True False  True]


Luego aplicamos la misma condición a los array relacionados.

Esto funciona porque 'distritos' y 'poblacion_proyectada' tienen la msima longitud y cada posición corresponde al mismo distrito.

In [36]:
distritos_filtrados = distritos[supera_limite]
poblacion_filtrada = poblacion_proyectada[supera_limite]

print("Distritos con más de 100 000 habitantes proyectados:")
for distrito, poblacion in zip(distritos_filtrados, poblacion_filtrada):
    print(f"- {distrito}: {poblacion:,} habitantes")

Distritos con más de 100 000 habitantes proyectados:
- Distrito Norte: 126,000 habitantes
- Distrito Este: 162,000 habitantes
- Distrito Centro: 218,000 habitantes


NumPy realizó el filtrado y el ciclo se utilizó únicamente para presentar los resultados de una forma legíble.

##### 10.7 Presentación del resumen completo

In [40]:
print("RESUMEN DEL ANÁLISIS")
print("-" * 55)

for i in range(len(distritos)):
    print(
        f"{distritos[i]:18} | "
        f"Registrada: {poblacion_registrada[i]:>7,} | "
        f"Proyectada: {poblacion_proyectada[i]:>7,} | "
        f"Crecimiento: {crecimiento_porcentual[i]:>5.2f}%"  
    )
    
print("-" * 55)
print(f"Promedio proyectado: {promedio_proyectado:,.2f}")
print(
    f"Mayor población: {distritos[indice_mayor]} "
    f"({poblacion_proyectada[indice_mayor]:,})"
)
print(
    f"Menor población: {distritos[indice_menor]}"
    f"({poblacion_proyectada[indice_menor]:,})"
)

RESUMEN DEL ANÁLISIS
-------------------------------------------------------
Distrito Norte     | Registrada: 120,000 | Proyectada: 126,000 | Crecimiento:  5.00%
Distrito Sur       | Registrada:  80,000 | Proyectada:  84,000 | Crecimiento:  5.00%
Distrito Este      | Registrada: 150,000 | Proyectada: 162,000 | Crecimiento:  8.00%
Distrito Oeste     | Registrada:  95,000 | Proyectada:  98,000 | Crecimiento:  3.16%
Distrito Centro    | Registrada: 200,000 | Proyectada: 218,000 | Crecimiento:  9.00%
-------------------------------------------------------
Promedio proyectado: 137,600.00
Mayor población: Distrito Centro (218,000)
Menor población: Distrito Sur(84,000)


In [38]:
range(len(distritos))

range(0, 5)

### 11. Práctica guiada

A partir de los datos del caso, resuelva las siguientes preguntas:
- ¿Cuál es la suma total de la población registrada?
- ¿Cuál es la suma total de la población proyectada?
- ¿Cuántos distritos tienen un crecimiento porcentual mayor que 5%?
- ¿Qué distritos tienen una población proyectada entre 90 000 y 180 000 habitantes?

Primero intente resolverlo. Luego revise la solución.

In [73]:
# MI INTENTO
 
# Población registrada total
poblacion_registrada_total = np.sum(poblacion_registrada)
print(f"población registrada total: {poblacion_registrada_total}")

# Población proyectada total
poblacion_proyectada_total = np.sum(poblacion_proyectada)
print(f"Población proyectada total: {poblacion_proyectada_total}")

# Número de distritos que tienen un crecimiento porcentual mayor que 5%
condicional = (((poblacion_proyectada - poblacion_registrada) / poblacion_registrada) * 100) > 5
distritos_mayor_5 = len(poblacion_proyectada[condicional])
los_distritos = distritos[condicional]

print(f"Cantidad de distritos con un crecimiento porcentual mayor que 5%: {distritos_mayor_5}  -> {los_distritos}")

# Distritos que tienen una población proyectada entre 90 000 y 180000
condional2 = (poblacion_proyectada >= 90000) & (poblacion_proyectada <= 180000)
distritos_mayor = distritos[condicional]
print(f"Distritos con población entre 90000 y 180000 habitantes: {distritos_mayor}")

población registrada total: 645000
Población proyectada total: 688000
Cantidad de distritos con un crecimiento porcentual mayor que 5%: 2  -> ['Distrito Este' 'Distrito Centro']
Distritos con población entre 90000 y 180000 habitantes: ['Distrito Este' 'Distrito Centro']


In [74]:
# Del profesedor:

# 1. Total de población registrada
total_registrada = np.sum(poblacion_registrada)

# 2. Total de población proyectada
total_proyectada = np.sum(poblacion_proyectada)

# 3. Cantidad de distritos con crecimiento mayor que 5 %
crecimiento_mayor_5 = crecimiento_porcentual > 5
cantidad_mayor_5 = np.sum(crecimiento_mayor_5)

# 4. Distritos con población proyectada entre 90 000 y 180 000
rango = (poblacion_proyectada >= 90000) & (poblacion_proyectada <= 180000)
distritos_en_rango = distritos[rango]

print("Total de población registrada:", f"{total_registrada:,}")
print("Total de población proyectada:", f"{total_proyectada:,}")
print("Distritos con crecimiento mayor que 5 %:", cantidad_mayor_5)
print("Distritos entre 90 000 y 180 000 habitantes:", distritos_en_rango)

Total de población registrada: 645,000
Total de población proyectada: 688,000
Distritos con crecimiento mayor que 5 %: 2
Distritos entre 90 000 y 180 000 habitantes: ['Distrito Norte' 'Distrito Este' 'Distrito Oeste']
