## NumPy

### 1. primeros pasos en NumPy

In [1]:
# Importando NumPy
import numpy

In [2]:
# Ejm:
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


NumPy como np
- generalmente se importa bajo el alias *np*

In [3]:
import numpy as np

In [4]:
# Ejm: Ahora se puede hacer referencia al paquete Numpy en np en lugar de numpy:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


Comprobando la versión de numpy

In [5]:
print(np.__version__)

2.3.5


### 2. Creación de array() (matrices) en NumPy

Crea un objeto ndarray de Numpy

NumPy se utiliza para trabajar con matrices. El objeto *array* in NumPy se llama *ndarray*.

Podemos crear un objeto NumPy *ndarray* utilizando la función *array()*

In [6]:
# Ejm:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Para crear un *ndarray*, podemos pasar una lista, una tupla o cualquier objeto tipo matriz al método *array()*, y se convertirá en un *ndarray*

In [7]:
# Ejm: Utilice una tupla para crear una matriz NumPy:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


#### 2.1 dimensiones en matrices array()

Una dimesión en matrices es un nivel de profundidad de matriz (matrices anidadas)
- matriz anidada: son matrices que tienen matrices como elementos

Matrices 0-D o escalares
- son los elementos de una matriz. Cada valor de una matriz es una matriz 0-D.

In [8]:
# Ejm: crea una matriz 0-D con valor 42:
arr = np.array(42)

print(arr)

42


Matrices unidimensionales
- Una matriz que tiene matrices 0-D como elementos se denomina matriz unidimensionales o 1-D
- Estas son las matrices más comunes y básicas.

In [9]:
# Ejm: crea una matriz 1-D que contenga los valores 1,2,3,4,5:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


Matrices 2D
- Una matriz que contiene matrices 1-D como elementos se denomina matriz 2-D.
- Estos se utilizan a menudo para representar matrices o tensores de segundo orden.

In [12]:
# Ejm: Crea una matriz 2-D que contenga dos matrices con los valores 1,2,3 y 4,5,6:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


Matrices 3D
- Una matriz que contiene 2-D (matrices) como elementos se llama matriz 3-D.
- Estos se utilizan a menudo para representar un tensor de tercer orden.

In [13]:
# Ejm: Cree una matriz tridimensional con dos matrices bidimensionales, ambas conteniendo dos matrices con los valores 1,2,3 y 4,5,6:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


¿Comprobar número de dimensiones?
- NumPy array proporciona el atributo *ndim* que devuelve un número entero que nos inidca cuántos dimensiones tiene la matriz.

In [15]:
# Ejm: Compruebe cuántas dimesiones tienen las matrices:

# Matriz 0-D o escalares:
arr = np.array(2)
# matriz 1-D o unidimensionales:
arr1 = np.array([1, 2, 3])
# Matriz 2-D o bidimensionales:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
# matriz 3-D o tridimensional:
arra3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# Dimensiones de matrices:
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arra3.ndim)

0
1
2
3


Matrices de dimensiones superiores
- Una matriz puede tener cualquier número de dimensiones.
- Cuando se crea la matriz, puede definir el número de dimensiones usando el argumento **ndmin**.

In [16]:
# Ejm: Crea una matriz con 5 dimensiones y verifica que tenga 5 dimensiones.
arr5 = np.array([1, 2, 3, 4], ndmin=5)

print(arr5)
print('numero de dimensiones :', arr5.ndim)

[[[[[1 2 3 4]]]]]
numero de dimensiones : 5


### 3. Indexación de matrices NumPy

#### 3.1 Acceder a elemtos de la matriz

la indexación de matrices es lo mismo que acceder a un elemento de una matriz.

Puede acceder a un elemento de la matriz haciendo referencia a su número de índice.

Los índices en las matrices NumPy comienzan con 0, lo que significa que el primer elemento tiene índice 0, y sucesivamente.

In [18]:
# Ejm: Obtenga el primer elemento de la siguiente matriz:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [19]:
# Ejm: Obtenga el segundo elemento de la matriz.
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [20]:
# Ejm: obtenga el tercer y cuarto elemento de la siguiente matriz y agréguelos.
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


#### 3.2 Accedea matrices 2D

Para acceder a elementos de matrices 2D podemos utilizar números enteros separados por comas que representan dimensión y el índice del elemento.

Piense en matrices 2-D como una tabla con filas y columnas, donde la dimensión representa la fila, y el índice representa la columna.


In [21]:
# Ejm: Accede al elemento de la primera fila, segunda columna:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2ndo elemento de la primera fila: ', arr[0, 1])

2ndo elemento de la primera fila:  2


In [22]:
# Ejm: Accede al elemento de la 2da fila, 5ta columna:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 4])

10


#### 3.3 Accede a matrices 3D

Para acceder a elementos de matrices tridimensionales podemos utilizar números enteros separados por comas que representan las dimensiones y el índice del elemento.

In [23]:
# Ejm: Acceda al tercer elemento de la segunda matriz de la primera matriz:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


#### 3.4 indexación negativa

Utilice indexación negativa para acceder a una matriz desde el final.

In [24]:
# Ejm: Imprima el último elemento de la segunda atenuación:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('ültimo elemento de la 2da dim: ', arr[1, -1])

ültimo elemento de la 2da dim:  10


### 4. Segmentación de matrices en NumPy

#### 4.1 Cortar matrices

Cortar en Python significa tomar elementos de un índice determinado a otro determinado índice.

- Pasamos segmeto en lugar de índice  de esta manera: **[start:end]**
- También podemos definir el paso, así: **[start:end:step]**

Si no pasamos en start se considera 0

Si no pasamos end de lu longitud considera de matriz en esa dimensión

Si no pasamos step se considera 1


In [25]:
# Ejm: Corte elementos del índice 1 al índice 5 de la siguiente matriz:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [26]:
# Ejm: corta elementos desde el índice 4 hasta el final de la matriz:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [27]:
# Ejm: Corta elementos desde el principio hasta el índice 4 (no incluido):
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


#### 4.1 Corte negativo

In [28]:
# Ejm: Corte del índice 3 del final hasta el índice 1 del final:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


#### 4.2 PASO - step

Utilice el valor step para determinar el paso del corte

In [ ]:
# Ejm: Devuelve todo los demás elementos del índice 1 al índice 5:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])  # paso 2 en 2

[2 4]


In [30]:
# Ejm: Devuelve todos los demás elementos de toda la matriz:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


#### 4.3 Cortar matrices 2D


In [31]:
# Ejm: Del segundo elemento, corte elementos del índice 1 al índice 4 (no incluido):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [34]:
# Ejm: De ambos elementos, devuelve el índice 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [35]:
# Ejm: de ambos elementos, corte el índice 1 al 4 (no incluye), esto devolverá una matriz bidimencional:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


### 5. NumPy Data Types

Tipos de datos en Python:
- string, integer, float, boolean, complex

Tipos de datos in NumPy:
- i: integer
- b: boolean
- u: integer sin signo
- f: float
- c: complex float
- m: timedelta
- M: datetime
- O: object - objeto
- S: string
- U: unicode - string unicode
- V: fragmento fijo de memoria para otro tipo (vacío)

#### 5.1 Comprobación del tipo de datos de una matriz
- la proíedad *dtype* devuelve el tipo de datos de la matriz

In [36]:
# Ejm: Obtener el tipo de datos de un objeto de matriz:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [37]:
# Ejm: Obtenga el tipo de dato de una matriz que contiene strings:
arr = np.array(["apple", "banana", "cherry"])

print(arr.dtype)

<U6


#### 5.2 Creación de matrices con un tipo de datos definido

- Usamos la función array() para crear matrices.
- dtype, nos permite definir el tipo de datos esperado de los elementos de la matriz

In [38]:
# Ejm: Crear una matriz con tipo de datos string:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


para i, u, f, S y U también podemos definir el tamaño.

In [39]:
# Ejm: Crea una matriz con un tipo de datos entero de 4 bytes:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


si se proporciona un tipo en el que no se puede convertir elementos, NumPy generará un ValueError.

In [42]:
# Ejm: Un string no entera com 'a' no0 se puede convertir a un integer:
#arr = np.array(['a', '2', '3'], dtype='i')

# forma correcta
arr = np.array(['1', '2', '3'], dtype='i')

print(arr)
print(arr.dtype)


[1 2 3]
int32


#### 5.3 Conversión de tipos de datos en matrices existentes

La mejor manera de cambiar el tipo de datos de una matriz existente es hacer una copia de la matriz con el método astype()

astype(): crea una copia de la matriz, y le permite especificar el tipo de datos como parámetro.

Los tipos de datos puedes especificar como 'i' o int

In [43]:
# Ejm: Cambie el tipo de datos de float a integer usando 'i' como valor de parámetro:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [44]:
# Ejm: Cambie el tipo de datos de float a integer usando int como valor de parámetro:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [45]:
# Ejm: cambie el tipo de datos de integer a boolean:
arr = np.array([1, 0, 3])

newarr = arr.astype('bool')

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


### 6 Copia y visualización de matrices de NumPy

La diferencia entre copiar y ver:
- copia: es una nueva matriz; es propietaria de los datos y cualquier cambio realizado no afecta la matriz original y cualquier cambio en la matriz original también no afecta la copia.
- vista: es solo una vista de la matriz original; *no es propietaria* de los datos y cualquier cambio realizado en cualquiera de ellos (copia o original) afecta a la otra matriz

#### 6.1 Copiar

In [46]:
# Ejm: Haga una copia, cambie la matriz original y muestre ambas matrices:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()

arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


#### 6.2 Vista

In [ ]:
# EJm: cree una vista, cambie la matriz original y muestre ambas matrices:
arr = np.array([1, 2, 3, 4, 5])

x = arr.view()  

arr[0] = 42

print(arr)
print(x)  # la vista debería verse afectada por los cambios realizados en la matriz original

[42  2  3  4  5]
[42  2  3  4  5]


Realizar cambios en la vista:

In [49]:
# Ejm: Cree una vista, cambie la vista y muestre ambas matrices:
arr = np.array([1, 2, 3, 4, 5])

x = arr.view()
x[0] = 42

print(arr)  # la matriz original debería verse afectada por los cambios realizados en la vista.
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


#### 6.3 Compruebe si array es propietario de sus datos

Cada matriz NumPy tiene el atributo 'base' que devuelve 'None' s i la matriz posee los datos. De lo contrario, el atributo 'base' hace referencia al objeto original.

In [50]:
# Ejm: imprima el valor del atributo base para verificar si una matriz posee sus datos o no:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


### 7. Forma de la matriz NumPy

Es el número de elementos en cada dimensión

#### 7.1 Obtener la forma de una matriz

Las matrices NumPy tienen un atributo llamado 'shape' que devuelve una tupla y cada índice tiene el número de elementos correspondientes.

In [ ]:
# Ejm: Imprima la forma de una matriz 2D:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr.shape)  # (2, 5) -> (,): 2 dim, 1ra dim tiene 2 elementos y la 2da dim tiene 5 elementos

(2, 5)


In [53]:
# Ejm: Crea una matriz con 5 dimensiones usando 'ndmin, usando un vector con los valores 1,2,3,4 
# y verifica que la última dimensión tenga el valor 4:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('forma del array:', arr.shape)


[[[[[1 2 3 4]]]]]
forma del array: (1, 1, 1, 1, 4)


¿Qué representa la tupla de shape?

Loa números enteros en cada índice indican la cantidad de elementos que tiene la dimensión correspondiente.

En el ejm anterior en el índice 4 tenemos el valor de 4, por lo que podemos decir que la quinta dimensión (4+1) tiene 4 elementos

### 8. Remodelación (reshape) de la matriz NumPy

remodelar significa cambiar la forma de una matriz.

La shape de un array es el número de elementos en cada dimensión.

Al reshape podemos agregar o eliminar dimensiones o cambiar el número de elementos en cada dimensión

#### 8.1 Remodelar de 1D a 2D

In [54]:
# Ejm: Convierta la siguiente matriz 1D con 12 elementos en una matriz 2D.
# La dimensión más extensa tendrá 4 matrices, cada una con 3 elementos:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 8.2 Remodelar de 1D a 3D

In [55]:
# Ejm: Convierta la siguiente matriz 1D con 12 elementos en un arrray 3D.
# La dimensión más extensa trendrá 2 arrays que contienen 3 arrays, cada una con 2 elementos:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


¿Podemos reshape en cualquier shape?

Sí, siempre y cuando los elementos necesarios para la reshape sean iguales en ambas formas

#### 8.3 ¿Devuelve copy o view?

In [56]:
# Ejm: Compruebe si la matriz devuelta es una copy o view:
arr = np.array([1, 2, 3, 4, 5, 6., 7, 8])

print(arr.reshape(2, 4).base)

[1. 2. 3. 4. 5. 6. 7. 8.]


#### 8.4 Dimensión desconocida

Se permite tener una dimensión "desconocida"(unknown)

Lo que significa que no es necesario especificar un número exacto para uno de los dimensiones en el método de reshape.

Pase -1 como un valor y NumPy lo hará calcular este número para tí.

In [60]:
# Ejm: Convierte una matriz 1D con 8 elementos a una matriz 3D con 2X2 elementos:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)  # no podemos pasar -1 a más de una dimensión

print(newarr)
print(newarr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
